name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - name: Add MSBuild to PATH
              uses: microsoft/setup-msbuild@v1.3.1
            - name: Build App
              run: |
                msbuild -version
                msbuild ShellLinkBinder\ShellLinkBinder.vcxproj -p:configuration=Release -p:platform=x64
                msbuild WinRLauncher\WinRLauncher.csproj -p:configuration=Release -p:platform=x64
